#
# Makefile.vars example
#
# This is some automake-imitation, except that it doesn't need
# a preprocessor.
#

CONFIG := debug

TARGET_LIBS += libhihi.so.9.9.9
LDFLAGS_libhihi := -ldl -Wl,-soname=libhihi.so.0
INSTDIR_libhihi := $(PREFIX)/lib
libhihi.so.9.9.9: libhihi.c hihi.h

TARGET_BINS += hihi
CFLAGS_hihi := -DHIHIHI
INSTDIR_hihi := $(PREFIX)/bin
hihi: hihi.c

TARGET_LNKS += libbplus.so.0
LNFLAGS_libbplus := -s libhihi.so.9.9.9
INSTDIR_libbplus := $(PREFIX)/lib

# End of Makefile.vars
